server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  application:
    name: core
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
